/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellDesignSystemRouteImport } from './routes/_shell.design-system'

const ShellDesignSystemRoute = ShellDesignSystemRouteImport.update({
  id: '/_shell/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/design-system': typeof ShellDesignSystemRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof ShellDesignSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell/design-system': typeof ShellDesignSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/design-system'
  fileRoutesByTo: FileRoutesByTo
  to: '/design-system'
  id: '__root__' | '/_shell/design-system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellDesignSystemRoute: typeof ShellDesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell/design-system': {
      id: '/_shell/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof ShellDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ShellDesignSystemRoute: ShellDesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
