/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAcademicRouteImport } from './routes/_shell.academic'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellDesignSystemRouteImport } from './routes/_shell.design-system'
import { Route as ShellExamRouteImport } from './routes/_shell.exam'
import { Route as ShellLearningRouteImport } from './routes/_shell.learning'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellAcademicIndexRouteImport } from './routes/_shell.academic.index'
import { Route as ShellAcademicEnrollmentsRouteImport } from './routes/_shell.academic.enrollments'
import { Route as ShellAcademicGroupsRouteImport } from './routes/_shell.academic.groups'
import { Route as ShellAcademicStudentsRouteImport } from './routes/_shell.academic.students'
import { Route as ShellAcademicTeachersRouteImport } from './routes/_shell.academic.teachers'
import { Route as ShellLearningIndexRouteImport } from './routes/_shell.learning.index'
import { Route as ShellLearningBookmarksRouteImport } from './routes/_shell.learning.bookmarks'
import { Route as ShellLearningContinueRouteImport } from './routes/_shell.learning.continue'
import { Route as ShellLearningCoursesCourseIdRouteImport } from './routes/_shell.learning.courses.$courseId'
import { Route as ShellLearningLessonsLessonIdRouteImport } from './routes/_shell.learning.lessons.$lessonId'
import { Route as ShellLearningModulesModuleIdRouteImport } from './routes/_shell.learning.modules.$moduleId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAcademicRoute = ShellAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDesignSystemRoute = ShellDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExamRoute = ShellExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLearningRoute = ShellLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAcademicIndexRoute = ShellAcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicEnrollmentsRoute =
  ShellAcademicEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => ShellAcademicRoute,
  } as any)
const ShellAcademicGroupsRoute = ShellAcademicGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicStudentsRoute = ShellAcademicStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicTeachersRoute = ShellAcademicTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellLearningIndexRoute = ShellLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellLearningBookmarksRoute = ShellLearningBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellLearningContinueRoute = ShellLearningContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellLearningCoursesCourseIdRoute =
  ShellLearningCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ShellLearningRoute,
  } as any)
const ShellLearningLessonsLessonIdRoute =
  ShellLearningLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ShellLearningRoute,
  } as any)
const ShellLearningModulesModuleIdRoute =
  ShellLearningModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => ShellLearningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/academic': typeof ShellAcademicRouteWithChildren
  '/admin': typeof ShellAdminRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/design-system': typeof ShellDesignSystemRoute
  '/exam': typeof ShellExamRoute
  '/learning': typeof ShellLearningRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/academic/groups': typeof ShellAcademicGroupsRoute
  '/academic/students': typeof ShellAcademicStudentsRoute
  '/academic/teachers': typeof ShellAcademicTeachersRoute
  '/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/learning/continue': typeof ShellLearningContinueRoute
  '/academic/': typeof ShellAcademicIndexRoute
  '/learning/': typeof ShellLearningIndexRoute
  '/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof ShellAdminRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/design-system': typeof ShellDesignSystemRoute
  '/exam': typeof ShellExamRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/academic/groups': typeof ShellAcademicGroupsRoute
  '/academic/students': typeof ShellAcademicStudentsRoute
  '/academic/teachers': typeof ShellAcademicTeachersRoute
  '/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/learning/continue': typeof ShellLearningContinueRoute
  '/academic': typeof ShellAcademicIndexRoute
  '/learning': typeof ShellLearningIndexRoute
  '/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_shell/academic': typeof ShellAcademicRouteWithChildren
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/design-system': typeof ShellDesignSystemRoute
  '/_shell/exam': typeof ShellExamRoute
  '/_shell/learning': typeof ShellLearningRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/_shell/academic/groups': typeof ShellAcademicGroupsRoute
  '/_shell/academic/students': typeof ShellAcademicStudentsRoute
  '/_shell/academic/teachers': typeof ShellAcademicTeachersRoute
  '/_shell/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/_shell/learning/continue': typeof ShellLearningContinueRoute
  '/_shell/academic/': typeof ShellAcademicIndexRoute
  '/_shell/learning/': typeof ShellLearningIndexRoute
  '/_shell/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/_shell/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/_shell/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/academic'
    | '/admin'
    | '/analytics'
    | '/design-system'
    | '/exam'
    | '/learning'
    | '/settings'
    | '/academic/enrollments'
    | '/academic/groups'
    | '/academic/students'
    | '/academic/teachers'
    | '/learning/bookmarks'
    | '/learning/continue'
    | '/academic/'
    | '/learning/'
    | '/learning/courses/$courseId'
    | '/learning/lessons/$lessonId'
    | '/learning/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/admin'
    | '/analytics'
    | '/design-system'
    | '/exam'
    | '/settings'
    | '/'
    | '/academic/enrollments'
    | '/academic/groups'
    | '/academic/students'
    | '/academic/teachers'
    | '/learning/bookmarks'
    | '/learning/continue'
    | '/academic'
    | '/learning'
    | '/learning/courses/$courseId'
    | '/learning/lessons/$lessonId'
    | '/learning/modules/$moduleId'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/_shell/academic'
    | '/_shell/admin'
    | '/_shell/analytics'
    | '/_shell/design-system'
    | '/_shell/exam'
    | '/_shell/learning'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/academic/enrollments'
    | '/_shell/academic/groups'
    | '/_shell/academic/students'
    | '/_shell/academic/teachers'
    | '/_shell/learning/bookmarks'
    | '/_shell/learning/continue'
    | '/_shell/academic/'
    | '/_shell/learning/'
    | '/_shell/learning/courses/$courseId'
    | '/_shell/learning/lessons/$lessonId'
    | '/_shell/learning/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForbiddenRoute: typeof ForbiddenRoute
  OfflineRoute: typeof OfflineRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/academic': {
      id: '/_shell/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof ShellAcademicRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/design-system': {
      id: '/_shell/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof ShellDesignSystemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exam': {
      id: '/_shell/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ShellExamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/learning': {
      id: '/_shell/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof ShellLearningRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/academic/': {
      id: '/_shell/academic/'
      path: '/'
      fullPath: '/academic/'
      preLoaderRoute: typeof ShellAcademicIndexRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/enrollments': {
      id: '/_shell/academic/enrollments'
      path: '/enrollments'
      fullPath: '/academic/enrollments'
      preLoaderRoute: typeof ShellAcademicEnrollmentsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/groups': {
      id: '/_shell/academic/groups'
      path: '/groups'
      fullPath: '/academic/groups'
      preLoaderRoute: typeof ShellAcademicGroupsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/students': {
      id: '/_shell/academic/students'
      path: '/students'
      fullPath: '/academic/students'
      preLoaderRoute: typeof ShellAcademicStudentsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/teachers': {
      id: '/_shell/academic/teachers'
      path: '/teachers'
      fullPath: '/academic/teachers'
      preLoaderRoute: typeof ShellAcademicTeachersRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/learning/': {
      id: '/_shell/learning/'
      path: '/'
      fullPath: '/learning/'
      preLoaderRoute: typeof ShellLearningIndexRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/bookmarks': {
      id: '/_shell/learning/bookmarks'
      path: '/bookmarks'
      fullPath: '/learning/bookmarks'
      preLoaderRoute: typeof ShellLearningBookmarksRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/continue': {
      id: '/_shell/learning/continue'
      path: '/continue'
      fullPath: '/learning/continue'
      preLoaderRoute: typeof ShellLearningContinueRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/courses/$courseId': {
      id: '/_shell/learning/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/learning/courses/$courseId'
      preLoaderRoute: typeof ShellLearningCoursesCourseIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/lessons/$lessonId': {
      id: '/_shell/learning/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/learning/lessons/$lessonId'
      preLoaderRoute: typeof ShellLearningLessonsLessonIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/modules/$moduleId': {
      id: '/_shell/learning/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/learning/modules/$moduleId'
      preLoaderRoute: typeof ShellLearningModulesModuleIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
  }
}

interface ShellAcademicRouteChildren {
  ShellAcademicEnrollmentsRoute: typeof ShellAcademicEnrollmentsRoute
  ShellAcademicGroupsRoute: typeof ShellAcademicGroupsRoute
  ShellAcademicStudentsRoute: typeof ShellAcademicStudentsRoute
  ShellAcademicTeachersRoute: typeof ShellAcademicTeachersRoute
  ShellAcademicIndexRoute: typeof ShellAcademicIndexRoute
}

const ShellAcademicRouteChildren: ShellAcademicRouteChildren = {
  ShellAcademicEnrollmentsRoute: ShellAcademicEnrollmentsRoute,
  ShellAcademicGroupsRoute: ShellAcademicGroupsRoute,
  ShellAcademicStudentsRoute: ShellAcademicStudentsRoute,
  ShellAcademicTeachersRoute: ShellAcademicTeachersRoute,
  ShellAcademicIndexRoute: ShellAcademicIndexRoute,
}

const ShellAcademicRouteWithChildren = ShellAcademicRoute._addFileChildren(
  ShellAcademicRouteChildren,
)

interface ShellLearningRouteChildren {
  ShellLearningBookmarksRoute: typeof ShellLearningBookmarksRoute
  ShellLearningContinueRoute: typeof ShellLearningContinueRoute
  ShellLearningIndexRoute: typeof ShellLearningIndexRoute
  ShellLearningCoursesCourseIdRoute: typeof ShellLearningCoursesCourseIdRoute
  ShellLearningLessonsLessonIdRoute: typeof ShellLearningLessonsLessonIdRoute
  ShellLearningModulesModuleIdRoute: typeof ShellLearningModulesModuleIdRoute
}

const ShellLearningRouteChildren: ShellLearningRouteChildren = {
  ShellLearningBookmarksRoute: ShellLearningBookmarksRoute,
  ShellLearningContinueRoute: ShellLearningContinueRoute,
  ShellLearningIndexRoute: ShellLearningIndexRoute,
  ShellLearningCoursesCourseIdRoute: ShellLearningCoursesCourseIdRoute,
  ShellLearningLessonsLessonIdRoute: ShellLearningLessonsLessonIdRoute,
  ShellLearningModulesModuleIdRoute: ShellLearningModulesModuleIdRoute,
}

const ShellLearningRouteWithChildren = ShellLearningRoute._addFileChildren(
  ShellLearningRouteChildren,
)

interface ShellRouteChildren {
  ShellAcademicRoute: typeof ShellAcademicRouteWithChildren
  ShellAdminRoute: typeof ShellAdminRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDesignSystemRoute: typeof ShellDesignSystemRoute
  ShellExamRoute: typeof ShellExamRoute
  ShellLearningRoute: typeof ShellLearningRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAcademicRoute: ShellAcademicRouteWithChildren,
  ShellAdminRoute: ShellAdminRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDesignSystemRoute: ShellDesignSystemRoute,
  ShellExamRoute: ShellExamRoute,
  ShellLearningRoute: ShellLearningRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  ForbiddenRoute: ForbiddenRoute,
  OfflineRoute: OfflineRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
