/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAcademicRouteImport } from './routes/_shell.academic'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellAssessmentRouteImport } from './routes/_shell.assessment'
import { Route as ShellDesignSystemRouteImport } from './routes/_shell.design-system'
import { Route as ShellExamRouteImport } from './routes/_shell.exam'
import { Route as ShellKnowledgeRouteImport } from './routes/_shell.knowledge'
import { Route as ShellLearningRouteImport } from './routes/_shell.learning'
import { Route as ShellPlatformRouteImport } from './routes/_shell.platform'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellAcademicIndexRouteImport } from './routes/_shell.academic.index'
import { Route as ShellAcademicEnrollmentsRouteImport } from './routes/_shell.academic.enrollments'
import { Route as ShellAcademicGroupsRouteImport } from './routes/_shell.academic.groups'
import { Route as ShellAcademicStudentsRouteImport } from './routes/_shell.academic.students'
import { Route as ShellAcademicTeachersRouteImport } from './routes/_shell.academic.teachers'
import { Route as ShellAnalyticsIndexRouteImport } from './routes/_shell.analytics.index'
import { Route as ShellAnalyticsAssessmentsRouteImport } from './routes/_shell.analytics.assessments'
import { Route as ShellAnalyticsClassesRouteImport } from './routes/_shell.analytics.classes'
import { Route as ShellAnalyticsPlatformRouteImport } from './routes/_shell.analytics.platform'
import { Route as ShellAssessmentIndexRouteImport } from './routes/_shell.assessment.index'
import { Route as ShellExamIndexRouteImport } from './routes/_shell.exam.index'
import { Route as ShellKnowledgeIndexRouteImport } from './routes/_shell.knowledge.index'
import { Route as ShellKnowledgeKindRouteImport } from './routes/_shell.knowledge.$kind'
import { Route as ShellKnowledgeFavoritesRouteImport } from './routes/_shell.knowledge.favorites'
import { Route as ShellKnowledgeSearchRouteImport } from './routes/_shell.knowledge.search'
import { Route as ShellLearningIndexRouteImport } from './routes/_shell.learning.index'
import { Route as ShellLearningBookmarksRouteImport } from './routes/_shell.learning.bookmarks'
import { Route as ShellLearningContinueRouteImport } from './routes/_shell.learning.continue'
import { Route as ShellPlatformIndexRouteImport } from './routes/_shell.platform.index'
import { Route as ShellPlatformAnnouncementsRouteImport } from './routes/_shell.platform.announcements'
import { Route as ShellPlatformAuditRouteImport } from './routes/_shell.platform.audit'
import { Route as ShellPlatformBrandingRouteImport } from './routes/_shell.platform.branding'
import { Route as ShellPlatformSettingsRouteImport } from './routes/_shell.platform.settings'
import { Route as ShellPlatformTenantsRouteImport } from './routes/_shell.platform.tenants'
import { Route as ShellPlatformUsersRouteImport } from './routes/_shell.platform.users'
import { Route as ShellAssessmentAssessmentsIndexRouteImport } from './routes/_shell.assessment.assessments.index'
import { Route as ShellAssessmentAssessmentsAssessmentIdRouteImport } from './routes/_shell.assessment.assessments.$assessmentId'
import { Route as ShellAssessmentQuestionsQuestionIdRouteImport } from './routes/_shell.assessment.questions.$questionId'
import { Route as ShellAssessmentQuestionsNewRouteImport } from './routes/_shell.assessment.questions.new'
import { Route as ShellExamAssessmentIdStartRouteImport } from './routes/_shell.exam.$assessmentId.start'
import { Route as ShellKnowledgeKindSlugRouteImport } from './routes/_shell.knowledge.$kind.$slug'
import { Route as ShellLearningCoursesCourseIdRouteImport } from './routes/_shell.learning.courses.$courseId'
import { Route as ShellLearningLessonsLessonIdRouteImport } from './routes/_shell.learning.lessons.$lessonId'
import { Route as ShellLearningModulesModuleIdRouteImport } from './routes/_shell.learning.modules.$moduleId'
import { Route as ShellExamAttemptsAttemptIdIndexRouteImport } from './routes/_shell.exam.attempts.$attemptId.index'
import { Route as ShellExamAttemptsAttemptIdResultRouteImport } from './routes/_shell.exam.attempts.$attemptId.result'
import { Route as ShellExamAttemptsAttemptIdReviewRouteImport } from './routes/_shell.exam.attempts.$attemptId.review'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAcademicRoute = ShellAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssessmentRoute = ShellAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDesignSystemRoute = ShellDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExamRoute = ShellExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeRoute = ShellKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLearningRoute = ShellLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlatformRoute = ShellPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAcademicIndexRoute = ShellAcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicEnrollmentsRoute =
  ShellAcademicEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => ShellAcademicRoute,
  } as any)
const ShellAcademicGroupsRoute = ShellAcademicGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicStudentsRoute = ShellAcademicStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAcademicTeachersRoute = ShellAcademicTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ShellAcademicRoute,
} as any)
const ShellAnalyticsIndexRoute = ShellAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAnalyticsRoute,
} as any)
const ShellAnalyticsAssessmentsRoute =
  ShellAnalyticsAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => ShellAnalyticsRoute,
  } as any)
const ShellAnalyticsClassesRoute = ShellAnalyticsClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ShellAnalyticsRoute,
} as any)
const ShellAnalyticsPlatformRoute = ShellAnalyticsPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => ShellAnalyticsRoute,
} as any)
const ShellAssessmentIndexRoute = ShellAssessmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAssessmentRoute,
} as any)
const ShellExamIndexRoute = ShellExamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellExamRoute,
} as any)
const ShellKnowledgeIndexRoute = ShellKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellKnowledgeRoute,
} as any)
const ShellKnowledgeKindRoute = ShellKnowledgeKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => ShellKnowledgeRoute,
} as any)
const ShellKnowledgeFavoritesRoute = ShellKnowledgeFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ShellKnowledgeRoute,
} as any)
const ShellKnowledgeSearchRoute = ShellKnowledgeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellKnowledgeRoute,
} as any)
const ShellLearningIndexRoute = ShellLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellLearningBookmarksRoute = ShellLearningBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellLearningContinueRoute = ShellLearningContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => ShellLearningRoute,
} as any)
const ShellPlatformIndexRoute = ShellPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellPlatformAnnouncementsRoute =
  ShellPlatformAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ShellPlatformRoute,
  } as any)
const ShellPlatformAuditRoute = ShellPlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellPlatformBrandingRoute = ShellPlatformBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellPlatformSettingsRoute = ShellPlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellPlatformTenantsRoute = ShellPlatformTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellPlatformUsersRoute = ShellPlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellPlatformRoute,
} as any)
const ShellAssessmentAssessmentsIndexRoute =
  ShellAssessmentAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => ShellAssessmentRoute,
  } as any)
const ShellAssessmentAssessmentsAssessmentIdRoute =
  ShellAssessmentAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => ShellAssessmentRoute,
  } as any)
const ShellAssessmentQuestionsQuestionIdRoute =
  ShellAssessmentQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => ShellAssessmentRoute,
  } as any)
const ShellAssessmentQuestionsNewRoute =
  ShellAssessmentQuestionsNewRouteImport.update({
    id: '/questions/new',
    path: '/questions/new',
    getParentRoute: () => ShellAssessmentRoute,
  } as any)
const ShellExamAssessmentIdStartRoute =
  ShellExamAssessmentIdStartRouteImport.update({
    id: '/$assessmentId/start',
    path: '/$assessmentId/start',
    getParentRoute: () => ShellExamRoute,
  } as any)
const ShellKnowledgeKindSlugRoute = ShellKnowledgeKindSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShellKnowledgeKindRoute,
} as any)
const ShellLearningCoursesCourseIdRoute =
  ShellLearningCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ShellLearningRoute,
  } as any)
const ShellLearningLessonsLessonIdRoute =
  ShellLearningLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ShellLearningRoute,
  } as any)
const ShellLearningModulesModuleIdRoute =
  ShellLearningModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => ShellLearningRoute,
  } as any)
const ShellExamAttemptsAttemptIdIndexRoute =
  ShellExamAttemptsAttemptIdIndexRouteImport.update({
    id: '/attempts/$attemptId/',
    path: '/attempts/$attemptId/',
    getParentRoute: () => ShellExamRoute,
  } as any)
const ShellExamAttemptsAttemptIdResultRoute =
  ShellExamAttemptsAttemptIdResultRouteImport.update({
    id: '/attempts/$attemptId/result',
    path: '/attempts/$attemptId/result',
    getParentRoute: () => ShellExamRoute,
  } as any)
const ShellExamAttemptsAttemptIdReviewRoute =
  ShellExamAttemptsAttemptIdReviewRouteImport.update({
    id: '/attempts/$attemptId/review',
    path: '/attempts/$attemptId/review',
    getParentRoute: () => ShellExamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/academic': typeof ShellAcademicRouteWithChildren
  '/admin': typeof ShellAdminRoute
  '/analytics': typeof ShellAnalyticsRouteWithChildren
  '/assessment': typeof ShellAssessmentRouteWithChildren
  '/design-system': typeof ShellDesignSystemRoute
  '/exam': typeof ShellExamRouteWithChildren
  '/knowledge': typeof ShellKnowledgeRouteWithChildren
  '/learning': typeof ShellLearningRouteWithChildren
  '/platform': typeof ShellPlatformRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/academic/groups': typeof ShellAcademicGroupsRoute
  '/academic/students': typeof ShellAcademicStudentsRoute
  '/academic/teachers': typeof ShellAcademicTeachersRoute
  '/analytics/assessments': typeof ShellAnalyticsAssessmentsRoute
  '/analytics/classes': typeof ShellAnalyticsClassesRoute
  '/analytics/platform': typeof ShellAnalyticsPlatformRoute
  '/knowledge/$kind': typeof ShellKnowledgeKindRouteWithChildren
  '/knowledge/favorites': typeof ShellKnowledgeFavoritesRoute
  '/knowledge/search': typeof ShellKnowledgeSearchRoute
  '/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/learning/continue': typeof ShellLearningContinueRoute
  '/platform/announcements': typeof ShellPlatformAnnouncementsRoute
  '/platform/audit': typeof ShellPlatformAuditRoute
  '/platform/branding': typeof ShellPlatformBrandingRoute
  '/platform/settings': typeof ShellPlatformSettingsRoute
  '/platform/tenants': typeof ShellPlatformTenantsRoute
  '/platform/users': typeof ShellPlatformUsersRoute
  '/academic/': typeof ShellAcademicIndexRoute
  '/analytics/': typeof ShellAnalyticsIndexRoute
  '/assessment/': typeof ShellAssessmentIndexRoute
  '/exam/': typeof ShellExamIndexRoute
  '/knowledge/': typeof ShellKnowledgeIndexRoute
  '/learning/': typeof ShellLearningIndexRoute
  '/platform/': typeof ShellPlatformIndexRoute
  '/assessment/assessments/$assessmentId': typeof ShellAssessmentAssessmentsAssessmentIdRoute
  '/assessment/questions/$questionId': typeof ShellAssessmentQuestionsQuestionIdRoute
  '/assessment/questions/new': typeof ShellAssessmentQuestionsNewRoute
  '/exam/$assessmentId/start': typeof ShellExamAssessmentIdStartRoute
  '/knowledge/$kind/$slug': typeof ShellKnowledgeKindSlugRoute
  '/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
  '/assessment/assessments/': typeof ShellAssessmentAssessmentsIndexRoute
  '/exam/attempts/$attemptId/result': typeof ShellExamAttemptsAttemptIdResultRoute
  '/exam/attempts/$attemptId/review': typeof ShellExamAttemptsAttemptIdReviewRoute
  '/exam/attempts/$attemptId/': typeof ShellExamAttemptsAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof ShellAdminRoute
  '/design-system': typeof ShellDesignSystemRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/academic/groups': typeof ShellAcademicGroupsRoute
  '/academic/students': typeof ShellAcademicStudentsRoute
  '/academic/teachers': typeof ShellAcademicTeachersRoute
  '/analytics/assessments': typeof ShellAnalyticsAssessmentsRoute
  '/analytics/classes': typeof ShellAnalyticsClassesRoute
  '/analytics/platform': typeof ShellAnalyticsPlatformRoute
  '/knowledge/$kind': typeof ShellKnowledgeKindRouteWithChildren
  '/knowledge/favorites': typeof ShellKnowledgeFavoritesRoute
  '/knowledge/search': typeof ShellKnowledgeSearchRoute
  '/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/learning/continue': typeof ShellLearningContinueRoute
  '/platform/announcements': typeof ShellPlatformAnnouncementsRoute
  '/platform/audit': typeof ShellPlatformAuditRoute
  '/platform/branding': typeof ShellPlatformBrandingRoute
  '/platform/settings': typeof ShellPlatformSettingsRoute
  '/platform/tenants': typeof ShellPlatformTenantsRoute
  '/platform/users': typeof ShellPlatformUsersRoute
  '/academic': typeof ShellAcademicIndexRoute
  '/analytics': typeof ShellAnalyticsIndexRoute
  '/assessment': typeof ShellAssessmentIndexRoute
  '/exam': typeof ShellExamIndexRoute
  '/knowledge': typeof ShellKnowledgeIndexRoute
  '/learning': typeof ShellLearningIndexRoute
  '/platform': typeof ShellPlatformIndexRoute
  '/assessment/assessments/$assessmentId': typeof ShellAssessmentAssessmentsAssessmentIdRoute
  '/assessment/questions/$questionId': typeof ShellAssessmentQuestionsQuestionIdRoute
  '/assessment/questions/new': typeof ShellAssessmentQuestionsNewRoute
  '/exam/$assessmentId/start': typeof ShellExamAssessmentIdStartRoute
  '/knowledge/$kind/$slug': typeof ShellKnowledgeKindSlugRoute
  '/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
  '/assessment/assessments': typeof ShellAssessmentAssessmentsIndexRoute
  '/exam/attempts/$attemptId/result': typeof ShellExamAttemptsAttemptIdResultRoute
  '/exam/attempts/$attemptId/review': typeof ShellExamAttemptsAttemptIdReviewRoute
  '/exam/attempts/$attemptId': typeof ShellExamAttemptsAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/offline': typeof OfflineRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_shell/academic': typeof ShellAcademicRouteWithChildren
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/analytics': typeof ShellAnalyticsRouteWithChildren
  '/_shell/assessment': typeof ShellAssessmentRouteWithChildren
  '/_shell/design-system': typeof ShellDesignSystemRoute
  '/_shell/exam': typeof ShellExamRouteWithChildren
  '/_shell/knowledge': typeof ShellKnowledgeRouteWithChildren
  '/_shell/learning': typeof ShellLearningRouteWithChildren
  '/_shell/platform': typeof ShellPlatformRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/academic/enrollments': typeof ShellAcademicEnrollmentsRoute
  '/_shell/academic/groups': typeof ShellAcademicGroupsRoute
  '/_shell/academic/students': typeof ShellAcademicStudentsRoute
  '/_shell/academic/teachers': typeof ShellAcademicTeachersRoute
  '/_shell/analytics/assessments': typeof ShellAnalyticsAssessmentsRoute
  '/_shell/analytics/classes': typeof ShellAnalyticsClassesRoute
  '/_shell/analytics/platform': typeof ShellAnalyticsPlatformRoute
  '/_shell/knowledge/$kind': typeof ShellKnowledgeKindRouteWithChildren
  '/_shell/knowledge/favorites': typeof ShellKnowledgeFavoritesRoute
  '/_shell/knowledge/search': typeof ShellKnowledgeSearchRoute
  '/_shell/learning/bookmarks': typeof ShellLearningBookmarksRoute
  '/_shell/learning/continue': typeof ShellLearningContinueRoute
  '/_shell/platform/announcements': typeof ShellPlatformAnnouncementsRoute
  '/_shell/platform/audit': typeof ShellPlatformAuditRoute
  '/_shell/platform/branding': typeof ShellPlatformBrandingRoute
  '/_shell/platform/settings': typeof ShellPlatformSettingsRoute
  '/_shell/platform/tenants': typeof ShellPlatformTenantsRoute
  '/_shell/platform/users': typeof ShellPlatformUsersRoute
  '/_shell/academic/': typeof ShellAcademicIndexRoute
  '/_shell/analytics/': typeof ShellAnalyticsIndexRoute
  '/_shell/assessment/': typeof ShellAssessmentIndexRoute
  '/_shell/exam/': typeof ShellExamIndexRoute
  '/_shell/knowledge/': typeof ShellKnowledgeIndexRoute
  '/_shell/learning/': typeof ShellLearningIndexRoute
  '/_shell/platform/': typeof ShellPlatformIndexRoute
  '/_shell/assessment/assessments/$assessmentId': typeof ShellAssessmentAssessmentsAssessmentIdRoute
  '/_shell/assessment/questions/$questionId': typeof ShellAssessmentQuestionsQuestionIdRoute
  '/_shell/assessment/questions/new': typeof ShellAssessmentQuestionsNewRoute
  '/_shell/exam/$assessmentId/start': typeof ShellExamAssessmentIdStartRoute
  '/_shell/knowledge/$kind/$slug': typeof ShellKnowledgeKindSlugRoute
  '/_shell/learning/courses/$courseId': typeof ShellLearningCoursesCourseIdRoute
  '/_shell/learning/lessons/$lessonId': typeof ShellLearningLessonsLessonIdRoute
  '/_shell/learning/modules/$moduleId': typeof ShellLearningModulesModuleIdRoute
  '/_shell/assessment/assessments/': typeof ShellAssessmentAssessmentsIndexRoute
  '/_shell/exam/attempts/$attemptId/result': typeof ShellExamAttemptsAttemptIdResultRoute
  '/_shell/exam/attempts/$attemptId/review': typeof ShellExamAttemptsAttemptIdReviewRoute
  '/_shell/exam/attempts/$attemptId/': typeof ShellExamAttemptsAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/academic'
    | '/admin'
    | '/analytics'
    | '/assessment'
    | '/design-system'
    | '/exam'
    | '/knowledge'
    | '/learning'
    | '/platform'
    | '/settings'
    | '/academic/enrollments'
    | '/academic/groups'
    | '/academic/students'
    | '/academic/teachers'
    | '/analytics/assessments'
    | '/analytics/classes'
    | '/analytics/platform'
    | '/knowledge/$kind'
    | '/knowledge/favorites'
    | '/knowledge/search'
    | '/learning/bookmarks'
    | '/learning/continue'
    | '/platform/announcements'
    | '/platform/audit'
    | '/platform/branding'
    | '/platform/settings'
    | '/platform/tenants'
    | '/platform/users'
    | '/academic/'
    | '/analytics/'
    | '/assessment/'
    | '/exam/'
    | '/knowledge/'
    | '/learning/'
    | '/platform/'
    | '/assessment/assessments/$assessmentId'
    | '/assessment/questions/$questionId'
    | '/assessment/questions/new'
    | '/exam/$assessmentId/start'
    | '/knowledge/$kind/$slug'
    | '/learning/courses/$courseId'
    | '/learning/lessons/$lessonId'
    | '/learning/modules/$moduleId'
    | '/assessment/assessments/'
    | '/exam/attempts/$attemptId/result'
    | '/exam/attempts/$attemptId/review'
    | '/exam/attempts/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/admin'
    | '/design-system'
    | '/settings'
    | '/'
    | '/academic/enrollments'
    | '/academic/groups'
    | '/academic/students'
    | '/academic/teachers'
    | '/analytics/assessments'
    | '/analytics/classes'
    | '/analytics/platform'
    | '/knowledge/$kind'
    | '/knowledge/favorites'
    | '/knowledge/search'
    | '/learning/bookmarks'
    | '/learning/continue'
    | '/platform/announcements'
    | '/platform/audit'
    | '/platform/branding'
    | '/platform/settings'
    | '/platform/tenants'
    | '/platform/users'
    | '/academic'
    | '/analytics'
    | '/assessment'
    | '/exam'
    | '/knowledge'
    | '/learning'
    | '/platform'
    | '/assessment/assessments/$assessmentId'
    | '/assessment/questions/$questionId'
    | '/assessment/questions/new'
    | '/exam/$assessmentId/start'
    | '/knowledge/$kind/$slug'
    | '/learning/courses/$courseId'
    | '/learning/lessons/$lessonId'
    | '/learning/modules/$moduleId'
    | '/assessment/assessments'
    | '/exam/attempts/$attemptId/result'
    | '/exam/attempts/$attemptId/review'
    | '/exam/attempts/$attemptId'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/forbidden'
    | '/offline'
    | '/unauthorized'
    | '/_shell/academic'
    | '/_shell/admin'
    | '/_shell/analytics'
    | '/_shell/assessment'
    | '/_shell/design-system'
    | '/_shell/exam'
    | '/_shell/knowledge'
    | '/_shell/learning'
    | '/_shell/platform'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/academic/enrollments'
    | '/_shell/academic/groups'
    | '/_shell/academic/students'
    | '/_shell/academic/teachers'
    | '/_shell/analytics/assessments'
    | '/_shell/analytics/classes'
    | '/_shell/analytics/platform'
    | '/_shell/knowledge/$kind'
    | '/_shell/knowledge/favorites'
    | '/_shell/knowledge/search'
    | '/_shell/learning/bookmarks'
    | '/_shell/learning/continue'
    | '/_shell/platform/announcements'
    | '/_shell/platform/audit'
    | '/_shell/platform/branding'
    | '/_shell/platform/settings'
    | '/_shell/platform/tenants'
    | '/_shell/platform/users'
    | '/_shell/academic/'
    | '/_shell/analytics/'
    | '/_shell/assessment/'
    | '/_shell/exam/'
    | '/_shell/knowledge/'
    | '/_shell/learning/'
    | '/_shell/platform/'
    | '/_shell/assessment/assessments/$assessmentId'
    | '/_shell/assessment/questions/$questionId'
    | '/_shell/assessment/questions/new'
    | '/_shell/exam/$assessmentId/start'
    | '/_shell/knowledge/$kind/$slug'
    | '/_shell/learning/courses/$courseId'
    | '/_shell/learning/lessons/$lessonId'
    | '/_shell/learning/modules/$moduleId'
    | '/_shell/assessment/assessments/'
    | '/_shell/exam/attempts/$attemptId/result'
    | '/_shell/exam/attempts/$attemptId/review'
    | '/_shell/exam/attempts/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForbiddenRoute: typeof ForbiddenRoute
  OfflineRoute: typeof OfflineRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/academic': {
      id: '/_shell/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof ShellAcademicRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assessment': {
      id: '/_shell/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof ShellAssessmentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/design-system': {
      id: '/_shell/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof ShellDesignSystemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exam': {
      id: '/_shell/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ShellExamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge': {
      id: '/_shell/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ShellKnowledgeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/learning': {
      id: '/_shell/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof ShellLearningRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/platform': {
      id: '/_shell/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof ShellPlatformRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/academic/': {
      id: '/_shell/academic/'
      path: '/'
      fullPath: '/academic/'
      preLoaderRoute: typeof ShellAcademicIndexRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/enrollments': {
      id: '/_shell/academic/enrollments'
      path: '/enrollments'
      fullPath: '/academic/enrollments'
      preLoaderRoute: typeof ShellAcademicEnrollmentsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/groups': {
      id: '/_shell/academic/groups'
      path: '/groups'
      fullPath: '/academic/groups'
      preLoaderRoute: typeof ShellAcademicGroupsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/students': {
      id: '/_shell/academic/students'
      path: '/students'
      fullPath: '/academic/students'
      preLoaderRoute: typeof ShellAcademicStudentsRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/academic/teachers': {
      id: '/_shell/academic/teachers'
      path: '/teachers'
      fullPath: '/academic/teachers'
      preLoaderRoute: typeof ShellAcademicTeachersRouteImport
      parentRoute: typeof ShellAcademicRoute
    }
    '/_shell/analytics/': {
      id: '/_shell/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof ShellAnalyticsIndexRouteImport
      parentRoute: typeof ShellAnalyticsRoute
    }
    '/_shell/analytics/assessments': {
      id: '/_shell/analytics/assessments'
      path: '/assessments'
      fullPath: '/analytics/assessments'
      preLoaderRoute: typeof ShellAnalyticsAssessmentsRouteImport
      parentRoute: typeof ShellAnalyticsRoute
    }
    '/_shell/analytics/classes': {
      id: '/_shell/analytics/classes'
      path: '/classes'
      fullPath: '/analytics/classes'
      preLoaderRoute: typeof ShellAnalyticsClassesRouteImport
      parentRoute: typeof ShellAnalyticsRoute
    }
    '/_shell/analytics/platform': {
      id: '/_shell/analytics/platform'
      path: '/platform'
      fullPath: '/analytics/platform'
      preLoaderRoute: typeof ShellAnalyticsPlatformRouteImport
      parentRoute: typeof ShellAnalyticsRoute
    }
    '/_shell/assessment/': {
      id: '/_shell/assessment/'
      path: '/'
      fullPath: '/assessment/'
      preLoaderRoute: typeof ShellAssessmentIndexRouteImport
      parentRoute: typeof ShellAssessmentRoute
    }
    '/_shell/exam/': {
      id: '/_shell/exam/'
      path: '/'
      fullPath: '/exam/'
      preLoaderRoute: typeof ShellExamIndexRouteImport
      parentRoute: typeof ShellExamRoute
    }
    '/_shell/knowledge/': {
      id: '/_shell/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ShellKnowledgeIndexRouteImport
      parentRoute: typeof ShellKnowledgeRoute
    }
    '/_shell/knowledge/$kind': {
      id: '/_shell/knowledge/$kind'
      path: '/$kind'
      fullPath: '/knowledge/$kind'
      preLoaderRoute: typeof ShellKnowledgeKindRouteImport
      parentRoute: typeof ShellKnowledgeRoute
    }
    '/_shell/knowledge/favorites': {
      id: '/_shell/knowledge/favorites'
      path: '/favorites'
      fullPath: '/knowledge/favorites'
      preLoaderRoute: typeof ShellKnowledgeFavoritesRouteImport
      parentRoute: typeof ShellKnowledgeRoute
    }
    '/_shell/knowledge/search': {
      id: '/_shell/knowledge/search'
      path: '/search'
      fullPath: '/knowledge/search'
      preLoaderRoute: typeof ShellKnowledgeSearchRouteImport
      parentRoute: typeof ShellKnowledgeRoute
    }
    '/_shell/learning/': {
      id: '/_shell/learning/'
      path: '/'
      fullPath: '/learning/'
      preLoaderRoute: typeof ShellLearningIndexRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/bookmarks': {
      id: '/_shell/learning/bookmarks'
      path: '/bookmarks'
      fullPath: '/learning/bookmarks'
      preLoaderRoute: typeof ShellLearningBookmarksRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/continue': {
      id: '/_shell/learning/continue'
      path: '/continue'
      fullPath: '/learning/continue'
      preLoaderRoute: typeof ShellLearningContinueRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/platform/': {
      id: '/_shell/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof ShellPlatformIndexRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/announcements': {
      id: '/_shell/platform/announcements'
      path: '/announcements'
      fullPath: '/platform/announcements'
      preLoaderRoute: typeof ShellPlatformAnnouncementsRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/audit': {
      id: '/_shell/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof ShellPlatformAuditRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/branding': {
      id: '/_shell/platform/branding'
      path: '/branding'
      fullPath: '/platform/branding'
      preLoaderRoute: typeof ShellPlatformBrandingRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/settings': {
      id: '/_shell/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof ShellPlatformSettingsRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/tenants': {
      id: '/_shell/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof ShellPlatformTenantsRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/platform/users': {
      id: '/_shell/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof ShellPlatformUsersRouteImport
      parentRoute: typeof ShellPlatformRoute
    }
    '/_shell/assessment/assessments/': {
      id: '/_shell/assessment/assessments/'
      path: '/assessments'
      fullPath: '/assessment/assessments/'
      preLoaderRoute: typeof ShellAssessmentAssessmentsIndexRouteImport
      parentRoute: typeof ShellAssessmentRoute
    }
    '/_shell/assessment/assessments/$assessmentId': {
      id: '/_shell/assessment/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessment/assessments/$assessmentId'
      preLoaderRoute: typeof ShellAssessmentAssessmentsAssessmentIdRouteImport
      parentRoute: typeof ShellAssessmentRoute
    }
    '/_shell/assessment/questions/$questionId': {
      id: '/_shell/assessment/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/assessment/questions/$questionId'
      preLoaderRoute: typeof ShellAssessmentQuestionsQuestionIdRouteImport
      parentRoute: typeof ShellAssessmentRoute
    }
    '/_shell/assessment/questions/new': {
      id: '/_shell/assessment/questions/new'
      path: '/questions/new'
      fullPath: '/assessment/questions/new'
      preLoaderRoute: typeof ShellAssessmentQuestionsNewRouteImport
      parentRoute: typeof ShellAssessmentRoute
    }
    '/_shell/exam/$assessmentId/start': {
      id: '/_shell/exam/$assessmentId/start'
      path: '/$assessmentId/start'
      fullPath: '/exam/$assessmentId/start'
      preLoaderRoute: typeof ShellExamAssessmentIdStartRouteImport
      parentRoute: typeof ShellExamRoute
    }
    '/_shell/knowledge/$kind/$slug': {
      id: '/_shell/knowledge/$kind/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$kind/$slug'
      preLoaderRoute: typeof ShellKnowledgeKindSlugRouteImport
      parentRoute: typeof ShellKnowledgeKindRoute
    }
    '/_shell/learning/courses/$courseId': {
      id: '/_shell/learning/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/learning/courses/$courseId'
      preLoaderRoute: typeof ShellLearningCoursesCourseIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/lessons/$lessonId': {
      id: '/_shell/learning/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/learning/lessons/$lessonId'
      preLoaderRoute: typeof ShellLearningLessonsLessonIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/learning/modules/$moduleId': {
      id: '/_shell/learning/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/learning/modules/$moduleId'
      preLoaderRoute: typeof ShellLearningModulesModuleIdRouteImport
      parentRoute: typeof ShellLearningRoute
    }
    '/_shell/exam/attempts/$attemptId/': {
      id: '/_shell/exam/attempts/$attemptId/'
      path: '/attempts/$attemptId'
      fullPath: '/exam/attempts/$attemptId/'
      preLoaderRoute: typeof ShellExamAttemptsAttemptIdIndexRouteImport
      parentRoute: typeof ShellExamRoute
    }
    '/_shell/exam/attempts/$attemptId/result': {
      id: '/_shell/exam/attempts/$attemptId/result'
      path: '/attempts/$attemptId/result'
      fullPath: '/exam/attempts/$attemptId/result'
      preLoaderRoute: typeof ShellExamAttemptsAttemptIdResultRouteImport
      parentRoute: typeof ShellExamRoute
    }
    '/_shell/exam/attempts/$attemptId/review': {
      id: '/_shell/exam/attempts/$attemptId/review'
      path: '/attempts/$attemptId/review'
      fullPath: '/exam/attempts/$attemptId/review'
      preLoaderRoute: typeof ShellExamAttemptsAttemptIdReviewRouteImport
      parentRoute: typeof ShellExamRoute
    }
  }
}

interface ShellAcademicRouteChildren {
  ShellAcademicEnrollmentsRoute: typeof ShellAcademicEnrollmentsRoute
  ShellAcademicGroupsRoute: typeof ShellAcademicGroupsRoute
  ShellAcademicStudentsRoute: typeof ShellAcademicStudentsRoute
  ShellAcademicTeachersRoute: typeof ShellAcademicTeachersRoute
  ShellAcademicIndexRoute: typeof ShellAcademicIndexRoute
}

const ShellAcademicRouteChildren: ShellAcademicRouteChildren = {
  ShellAcademicEnrollmentsRoute: ShellAcademicEnrollmentsRoute,
  ShellAcademicGroupsRoute: ShellAcademicGroupsRoute,
  ShellAcademicStudentsRoute: ShellAcademicStudentsRoute,
  ShellAcademicTeachersRoute: ShellAcademicTeachersRoute,
  ShellAcademicIndexRoute: ShellAcademicIndexRoute,
}

const ShellAcademicRouteWithChildren = ShellAcademicRoute._addFileChildren(
  ShellAcademicRouteChildren,
)

interface ShellAnalyticsRouteChildren {
  ShellAnalyticsAssessmentsRoute: typeof ShellAnalyticsAssessmentsRoute
  ShellAnalyticsClassesRoute: typeof ShellAnalyticsClassesRoute
  ShellAnalyticsPlatformRoute: typeof ShellAnalyticsPlatformRoute
  ShellAnalyticsIndexRoute: typeof ShellAnalyticsIndexRoute
}

const ShellAnalyticsRouteChildren: ShellAnalyticsRouteChildren = {
  ShellAnalyticsAssessmentsRoute: ShellAnalyticsAssessmentsRoute,
  ShellAnalyticsClassesRoute: ShellAnalyticsClassesRoute,
  ShellAnalyticsPlatformRoute: ShellAnalyticsPlatformRoute,
  ShellAnalyticsIndexRoute: ShellAnalyticsIndexRoute,
}

const ShellAnalyticsRouteWithChildren = ShellAnalyticsRoute._addFileChildren(
  ShellAnalyticsRouteChildren,
)

interface ShellAssessmentRouteChildren {
  ShellAssessmentIndexRoute: typeof ShellAssessmentIndexRoute
  ShellAssessmentAssessmentsAssessmentIdRoute: typeof ShellAssessmentAssessmentsAssessmentIdRoute
  ShellAssessmentQuestionsQuestionIdRoute: typeof ShellAssessmentQuestionsQuestionIdRoute
  ShellAssessmentQuestionsNewRoute: typeof ShellAssessmentQuestionsNewRoute
  ShellAssessmentAssessmentsIndexRoute: typeof ShellAssessmentAssessmentsIndexRoute
}

const ShellAssessmentRouteChildren: ShellAssessmentRouteChildren = {
  ShellAssessmentIndexRoute: ShellAssessmentIndexRoute,
  ShellAssessmentAssessmentsAssessmentIdRoute:
    ShellAssessmentAssessmentsAssessmentIdRoute,
  ShellAssessmentQuestionsQuestionIdRoute:
    ShellAssessmentQuestionsQuestionIdRoute,
  ShellAssessmentQuestionsNewRoute: ShellAssessmentQuestionsNewRoute,
  ShellAssessmentAssessmentsIndexRoute: ShellAssessmentAssessmentsIndexRoute,
}

const ShellAssessmentRouteWithChildren = ShellAssessmentRoute._addFileChildren(
  ShellAssessmentRouteChildren,
)

interface ShellExamRouteChildren {
  ShellExamIndexRoute: typeof ShellExamIndexRoute
  ShellExamAssessmentIdStartRoute: typeof ShellExamAssessmentIdStartRoute
  ShellExamAttemptsAttemptIdResultRoute: typeof ShellExamAttemptsAttemptIdResultRoute
  ShellExamAttemptsAttemptIdReviewRoute: typeof ShellExamAttemptsAttemptIdReviewRoute
  ShellExamAttemptsAttemptIdIndexRoute: typeof ShellExamAttemptsAttemptIdIndexRoute
}

const ShellExamRouteChildren: ShellExamRouteChildren = {
  ShellExamIndexRoute: ShellExamIndexRoute,
  ShellExamAssessmentIdStartRoute: ShellExamAssessmentIdStartRoute,
  ShellExamAttemptsAttemptIdResultRoute: ShellExamAttemptsAttemptIdResultRoute,
  ShellExamAttemptsAttemptIdReviewRoute: ShellExamAttemptsAttemptIdReviewRoute,
  ShellExamAttemptsAttemptIdIndexRoute: ShellExamAttemptsAttemptIdIndexRoute,
}

const ShellExamRouteWithChildren = ShellExamRoute._addFileChildren(
  ShellExamRouteChildren,
)

interface ShellKnowledgeKindRouteChildren {
  ShellKnowledgeKindSlugRoute: typeof ShellKnowledgeKindSlugRoute
}

const ShellKnowledgeKindRouteChildren: ShellKnowledgeKindRouteChildren = {
  ShellKnowledgeKindSlugRoute: ShellKnowledgeKindSlugRoute,
}

const ShellKnowledgeKindRouteWithChildren =
  ShellKnowledgeKindRoute._addFileChildren(ShellKnowledgeKindRouteChildren)

interface ShellKnowledgeRouteChildren {
  ShellKnowledgeKindRoute: typeof ShellKnowledgeKindRouteWithChildren
  ShellKnowledgeFavoritesRoute: typeof ShellKnowledgeFavoritesRoute
  ShellKnowledgeSearchRoute: typeof ShellKnowledgeSearchRoute
  ShellKnowledgeIndexRoute: typeof ShellKnowledgeIndexRoute
}

const ShellKnowledgeRouteChildren: ShellKnowledgeRouteChildren = {
  ShellKnowledgeKindRoute: ShellKnowledgeKindRouteWithChildren,
  ShellKnowledgeFavoritesRoute: ShellKnowledgeFavoritesRoute,
  ShellKnowledgeSearchRoute: ShellKnowledgeSearchRoute,
  ShellKnowledgeIndexRoute: ShellKnowledgeIndexRoute,
}

const ShellKnowledgeRouteWithChildren = ShellKnowledgeRoute._addFileChildren(
  ShellKnowledgeRouteChildren,
)

interface ShellLearningRouteChildren {
  ShellLearningBookmarksRoute: typeof ShellLearningBookmarksRoute
  ShellLearningContinueRoute: typeof ShellLearningContinueRoute
  ShellLearningIndexRoute: typeof ShellLearningIndexRoute
  ShellLearningCoursesCourseIdRoute: typeof ShellLearningCoursesCourseIdRoute
  ShellLearningLessonsLessonIdRoute: typeof ShellLearningLessonsLessonIdRoute
  ShellLearningModulesModuleIdRoute: typeof ShellLearningModulesModuleIdRoute
}

const ShellLearningRouteChildren: ShellLearningRouteChildren = {
  ShellLearningBookmarksRoute: ShellLearningBookmarksRoute,
  ShellLearningContinueRoute: ShellLearningContinueRoute,
  ShellLearningIndexRoute: ShellLearningIndexRoute,
  ShellLearningCoursesCourseIdRoute: ShellLearningCoursesCourseIdRoute,
  ShellLearningLessonsLessonIdRoute: ShellLearningLessonsLessonIdRoute,
  ShellLearningModulesModuleIdRoute: ShellLearningModulesModuleIdRoute,
}

const ShellLearningRouteWithChildren = ShellLearningRoute._addFileChildren(
  ShellLearningRouteChildren,
)

interface ShellPlatformRouteChildren {
  ShellPlatformAnnouncementsRoute: typeof ShellPlatformAnnouncementsRoute
  ShellPlatformAuditRoute: typeof ShellPlatformAuditRoute
  ShellPlatformBrandingRoute: typeof ShellPlatformBrandingRoute
  ShellPlatformSettingsRoute: typeof ShellPlatformSettingsRoute
  ShellPlatformTenantsRoute: typeof ShellPlatformTenantsRoute
  ShellPlatformUsersRoute: typeof ShellPlatformUsersRoute
  ShellPlatformIndexRoute: typeof ShellPlatformIndexRoute
}

const ShellPlatformRouteChildren: ShellPlatformRouteChildren = {
  ShellPlatformAnnouncementsRoute: ShellPlatformAnnouncementsRoute,
  ShellPlatformAuditRoute: ShellPlatformAuditRoute,
  ShellPlatformBrandingRoute: ShellPlatformBrandingRoute,
  ShellPlatformSettingsRoute: ShellPlatformSettingsRoute,
  ShellPlatformTenantsRoute: ShellPlatformTenantsRoute,
  ShellPlatformUsersRoute: ShellPlatformUsersRoute,
  ShellPlatformIndexRoute: ShellPlatformIndexRoute,
}

const ShellPlatformRouteWithChildren = ShellPlatformRoute._addFileChildren(
  ShellPlatformRouteChildren,
)

interface ShellRouteChildren {
  ShellAcademicRoute: typeof ShellAcademicRouteWithChildren
  ShellAdminRoute: typeof ShellAdminRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRouteWithChildren
  ShellAssessmentRoute: typeof ShellAssessmentRouteWithChildren
  ShellDesignSystemRoute: typeof ShellDesignSystemRoute
  ShellExamRoute: typeof ShellExamRouteWithChildren
  ShellKnowledgeRoute: typeof ShellKnowledgeRouteWithChildren
  ShellLearningRoute: typeof ShellLearningRouteWithChildren
  ShellPlatformRoute: typeof ShellPlatformRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAcademicRoute: ShellAcademicRouteWithChildren,
  ShellAdminRoute: ShellAdminRoute,
  ShellAnalyticsRoute: ShellAnalyticsRouteWithChildren,
  ShellAssessmentRoute: ShellAssessmentRouteWithChildren,
  ShellDesignSystemRoute: ShellDesignSystemRoute,
  ShellExamRoute: ShellExamRouteWithChildren,
  ShellKnowledgeRoute: ShellKnowledgeRouteWithChildren,
  ShellLearningRoute: ShellLearningRouteWithChildren,
  ShellPlatformRoute: ShellPlatformRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  ForbiddenRoute: ForbiddenRoute,
  OfflineRoute: OfflineRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
